module Api
  module V1
    class PayslipsController < ApplicationController
      before_action :set_payroll_run, only: :index
      before_action :set_employee, only: :employee_index
      before_action :set_payslip, only: :show

      def index
        payslips = @payroll_run.payslips
                                .includes(:employee)
                                .order(created_at: :desc)

        render json: {
          data: payslips.map do |payslip|
            PayslipSerializer.new(payslip).as_json
          end
        }
      end

      def employee_index
        payslips = @employee.payslips
                            .includes(:payroll_run)
                            .order(created_at: :desc)

        render json: {
          data: payslips.map do |payslip|
            PayslipSerializer.new(payslip).as_json
          end
        }
      end

      def show
        render json: {
          data: PayslipSerializer.new(@payslip).as_json
        }
      end

      def export
        payslip = Payslip
          .includes(:employee, :payroll_run, :payslip_items)
          .find(params[:id])

        case params[:format]
        when "pdf"
          export_pdf(payslip)
        else
          render json: {
            error: {
              code: "UNSUPPORTED_FORMAT",
              message: "Supported format is pdf"
            }
          }, status: :bad_request
        end
      end

      private

      def set_payroll_run
        @payroll_run = PayrollRun.find(params[:payroll_run_id])
      end

      def set_employee
        @employee = Employee.find(params[:id])
      end

      def set_payslip
        @payslip = Payslip.find(params[:id])
      end

      def export_pdf(payslip)
  pdf = Prawn::Document.new(
    page_size: "A4",
    margin: 40
  )

  currency = payslip.payroll_run.currency

  pdf.text "SalaryHub", size: 24, style: :bold
  pdf.text "Payslip", size: 18, style: :bold
  pdf.move_down 20

  pdf.stroke_horizontal_rule
  pdf.move_down 15

  pdf.text payslip.employee.full_name, size: 16, style: :bold
  pdf.move_down 5

  pdf.text(
    "#{payslip.employee.employee_code} · #{payslip.employee.email}",
    size: 10
  )

  pdf.move_down 5

  pdf.text(
    "Payroll Period: #{payslip.payroll_run.payroll_period} · Currency: #{currency}",
    size: 10
  )

  pdf.move_down 25

  pdf.text "Payroll Summary", size: 14, style: :bold
  pdf.move_down 10

  pdf.table(
    [
      ["Working Days", "Paid Days", "Gross Earnings", "Net Pay"],
      [
        payslip.working_days.to_s,
        payslip.paid_days.to_s,
        format_money(payslip.gross_earnings, currency),
        format_money(payslip.net_pay, currency)
      ]
    ],
    width: pdf.bounds.width,
    cell_style: {
      padding: 8,
      borders: [:bottom]
    },
    header: true
  )

  pdf.move_down 25

  pdf.text "Earnings & Deductions", size: 14, style: :bold
  pdf.move_down 10

  rows = [
    ["Code", "Description", "Type", "Amount"]
  ]

  payslip.payslip_items.order(:created_at).each do |item|
    rows << [
      item.code,
      item.description || "—",
      item.item_type.titleize,
      format_money(item.amount, currency)
    ]
  end

  pdf.table(
    rows,
    width: pdf.bounds.width,
    header: true,
    cell_style: {
      padding: 7,
      size: 9
    }
  )

  pdf.move_down 25

  pdf.text(
    "Net Pay: #{format_money(payslip.net_pay, currency)}",
    size: 18,
    style: :bold,
    align: :right
  )

  pdf.move_down 35

  pdf.text(
    "Generated by SalaryHub",
    size: 8,
    align: :center
  )

  send_data pdf.render,
            filename: "payslip-#{payslip.employee.employee_code}-#{payslip.payroll_run.payroll_period}.pdf",
            type: "application/pdf",
            disposition: "attachment"
end


def format_money(amount, currency)
  "#{currency} #{format('%.2f', amount)}"
end
    end
  end
end